// Error
// 0
try {
    throw "Error";
}
catch err {
    print(err);
}